version: '2'

services:
  service:
    image: regsethu/testcandidatelauncher:1.0.0
    working_dir: /data
    volumes:
      - $PWD/service:/data
    ports:
      - "3001:3001"
    command: |
      /bin/bash -c \
      "npm install && \
       serverless offline start --port 3001 --host 0.0.0.0 --corsAllowOrigin '*'"

  webapp:
    image: regsethu/testcandidatelauncher:1.0.0
    working_dir: /data
    volumes:
      - $PWD/webapp:/data
    ports:
      - "3000:3000"  
    command: |
      /bin/bash -c \
      "yarn install && \
       REACT_APP_API_URL="http://localhost:3001" yarn build && \
       http-server build -p 3000"  
 

